version: '3'
services:
  client:
    build: ./client
    ports:
      - "3000:80"
    #stdin_open: true


  server:
    build: ./server
    command: gunicorn --bind 0.0.0.0:8080 app:app
    ports:
      - "8080:8080"
